import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Guides',
        description: 'Step-by-step guides for using AI in your development workflow.',
        slug: '/guides',
      },
      items: [
        {
          type: 'category',
          label: 'Getting Started',
          items: [
            'quickstart',
            'setup/web-and-backend',
            'setup/dotnet',
            'setup/firmware',
          ],
        },
        {
          type: 'category',
          label: 'Starter',
          items: [
            'guides/starter/setup',
            'guides/starter/workflow',
          ],
        },
        {
          type: 'category',
          label: 'Intermediate',
          items: [
            'guides/intermediate/setup',
            'guides/intermediate/workflow',
          ],
        },
        {
          type: 'category',
          label: 'Pro',
          items: [
            'guides/pro/setup',
            'guides/pro/workflow',
          ],
        },
        'guides/prd',
        {
          type: 'category',
          label: 'Prompting',
          items: [
            'prompting/basics',
            'prompting/advanced',
          ],
        },
        {
          type: 'category',
          label: 'Code Generation & Debugging',
          items: [
            'code/generation',
            'code/debugging',
            'code/refactoring',
          ],
        },
        {
          type: 'category',
          label: 'Testing with AI',
          items: [
            'testing/unit-tests',
            'testing/coverage',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Claude Code',
      link: {
        type: 'generated-index',
        title: 'Claude Code',
        description: 'Deep-dive into Claude Code capabilities and features.',
        slug: '/claude-code',
      },
      items: [
        'claude-code/memory',
        'claude-code/commands',
        'claude-code/context',
        'claude-code/permissions',
        'claude-code/auto-mode',
        'claude-code/flags',
        'claude-code/skills',
        'claude-code/subagents',
        'claude-code/hooks',
        'claude-code/mcp',
        'claude-code/plugins',
        'claude-code/workflows',
        'claude-code/agent-teams',
        'claude-code/tmux',
        'claude-code/debugging',
        'claude-code/tips',
      ],
    },
    {
      type: 'category',
      label: 'Codex',
      link: {
        type: 'generated-index',
        title: 'Codex',
        description: 'Deep-dive into OpenAI Codex capabilities and features. Start with the Codex overview under More Tools for installation and authentication.',
        slug: '/codex',
      },
      items: [
        'codex/agents-md',
        'codex/commands',
        'codex/context',
        'codex/permissions',
        'codex/auto-review',
        'codex/flags',
        'codex/skills',
        'codex/subagents',
        'codex/hooks',
        'codex/mcp',
        'codex/plugins',
        'codex/automation',
        'codex/cloud',
        'codex/worktrees',
        'codex/debugging',
        'codex/tips',
      ],
    },
    {
      type: 'category',
      label: 'Cursor',
      link: {
        type: 'generated-index',
        title: 'Cursor',
        description: 'Deep-dive into Cursor capabilities and features. Start with the Cursor overview under More Tools for installation and the editor basics.',
        slug: '/cursor',
      },
      items: [
        'cursor/rules',
        'cursor/commands',
        'cursor/context',
        'cursor/permissions',
        'cursor/modes',
        'cursor/cli',
        'cursor/skills',
        'cursor/subagents',
        'cursor/hooks',
        'cursor/mcp',
        'cursor/plugins',
        'cursor/cloud-agents',
        'cursor/parallel-agents',
        'cursor/review',
        'cursor/debugging',
        'cursor/tips',
      ],
    },
    {
      type: 'category',
      label: 'More Tools',
      link: {
        type: 'generated-index',
        title: 'More Tools',
        description: 'Overview and comparison of AI development tools.',
        slug: '/tools',
      },
      items: [
        'tools/overview',
        'tools/cursor',
        'tools/github-copilot',
        'tools/codex',
        'tools/gemini-cli',
        'tools/aider',
        'tools/mistral',
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      link: {
        type: 'generated-index',
        title: 'Resources',
        description: 'Additional resources and references.',
        slug: '/resources',
      },
      items: [
        'resources/github-repos',
        'resources/prompt-templates',
        'resources/troubleshooting',
      ],
    },
  ],
};

export default sidebars;
